### ISSUE TITLE
预览图片的时候闪退

### ISSUE THREAD

**Issue by zhangkun0018** [JiangHaiYang01/WeChatPhoto#3]
华为nova 5i   Android10
预览图片时闪退
![1600146416(1)](https://user-images.githubusercontent.com/23331766/93168105-b6898200-f754-11ea-8063-4ad6f108d129.png)

**Comment by JiangHaiYang01** [comment]
这个版本用的是多少的版本，能说一下么 我这边好修复

**Comment by zhangkun0018** [comment]
就是最新的版本0.0.4
