### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by WWGsky** [JiangHaiYang01/WeChatPhoto#4]
Java中调用!!  Java中调用!!  Java中调用!!
1.调用 Larger.create().XXX.start(context) 进入大图浏览页之后,顶部状态栏没有适配.
2.下载App进行体验时,频繁触发 Leak
3.调用 Larger.create().XXX.start(context) 进入大图浏览页之后,拖拽无反应

playImage_oneImg = (ImageView) findViewById(R.id.playImage_oneImg);

private List<Bean> list;
private List<ImageView> imgList;
imgList = new ArrayList<>();
imgList.add(playImage_oneImg);

list = new ArrayList<>();
Bean bean = new Bean();
bean.setFullUrl(beanUrl);
list.add(bean);

@Override
    public void onClick(View v) {
        switch (v.getId()) {
            default:
                break;
            case R.id.playImage_oneImg:

                Larger.INSTANCE.create()
                        .withSingle()//这里展示的单个view
                        .setImageLoad(new GlideImageLoader(PlayImageActivity.this))   //图片加载器
                        .setImagesWithSingle(imgList)//设置imageView
                        .setData(list) //添加默认的数据源
                        .start(PlayImageActivity.this);

//                Larger.INSTANCE.create()
//                        .withSingle()//这里展示的是列表类型的
//                        .setImageLoad(new GlideImageLoader(PlayImageActivity.this))   //图片加载器
//                        .setCustomListener(R.layout.image_show_big,R.id.big_img,点击自定义的按钮)//自定义布局
//                        .setData(list) //添加默认的数据源
//                        .start(PlayImageActivity.this);//跳转

                break;
        }
    }

@SuppressLint("ParcelCreator")
    private class Bean extends LargerBean{

        @NotNull
        @Override
        public LargerDataEnum getType() {
            return LargerDataEnum.IMAGE;
        }

        @Override
        public int describeContents() {
            return 0;
        }

        @Override
        public void writeToParcel(Parcel dest, int flags) {

        }
    }

**Comment by JiangHaiYang01** [comment]
感谢您的issues  
1.拖拽无反应的问题，我在最新的代码中已经修改了，代码已经提交，做了优化处理，
并且加入可以上滑动的入口             withListType.setUpCanMove(true)//向上滑动有效
2.状态栏没有适配，这边默认就是没有状态栏的，微信和一般的大图浏览都讲这个去掉的
3.频繁的leak 我这边先看一下，确认问题之后在做提交
