### ISSUE TITLE
项目使用java写的，是不是不能用了

### ISSUE THREAD

**Issue by love-bk** [JiangHaiYang01/WeChatPhoto#5]

**Comment by JiangHaiYang01** [comment]
kotlin 和java 可以相互调用啊。 笔者这里提供的是思路哈。很多细节笔者并没有进行优化。实在是比较忙，等空下来了，将此项目优化和维护一下。 如果项目中要使用此功能，可以将源码放到项目中。有问题可以进行更改。如果有好的建议。可以提供 issues 

笔者空了。会优化此项目的
